#!/usr/bin/env bash
#print a script that display 1 to 100, Fizzbuzz when number is multiple of 3 and 5, Fizz when multiple of 3 and Buzz when multipl ef 5

 i=1
while [ $i -le 100 ]; do
	if [ $(($i%3)) -eq 0 ] && [ $(($i%5)) -eq 0 ]; then
		echo 'FizzBuzz'
	elif [ $(($i%3)) -eq 0 ]; then
		echo 'Fizz'
	elif [ $(($i%5)) -eq 0 ]; then
		echo 'Buzz'
	else
		echo "$i"
	fi
	((i++))
done
