#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20: display 4 and then bad luck from China for the 4th loop iteration, 9 and then bad luck from Japan for the 9th loop iteration, 17 and then bad luck from Italy for the 17th loop iteration

 i=1
while [ $i -le 20 ];do
    case $i in
        4)
            echo -e "$i \nbad luck from China" ;;
        9)
            echo -e "$i \nbad luck from Japan" ;;
        17)
            echo -e "$i \nbad luck from Italy" ;;
	*)
            echo $i ;;
    esac
    ((i++))
done
