#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:display hours from 0 to 12 and minutes from 1 to 59
echo 'Hour:0'
 i=1
while [ $i -le 59 ];do
    echo "$i"
    ((i++))
done
echo 'Hour:1'
    j=1
    while [ $j -le 12 ];do
        echo "$j"
        ((j++))
    done
