#!/usr/bin/env bash
#write a script that creates the file /var/run/myscript.pid containing its PID
#displays "To infinity and beyond" indefinitely, "I hate the kill command" when receiving a SIGTERM signal, displays "Y U no love me?!" when receiving a SIGINT signal
#deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap 'echo "I hate the kill command";rm -f /var/run/myscript.pid;exit 0' SIGTERM
trap 'echo "Y U no love me?!";rm -f /var/run/myscript.pid;exit 0' SIGINT

pid=$(pgrep -o "/var/run/myscript.pid")
echo "$pid" > /var/run/myscript.pid

while true;do
    echo "To infinity and beyond"
    sleep 2
done


