#!/usr/bin/env bash
#a script that Indefinitely writes I am alive! to the file /tmp/my_process, with a 2 second pause between every message

while true;do
    echo "I am alive!" >> /tmp/my_process
    sleep 2 
done
